### ISSUE TITLE
Objective function for solving vacuum equilibrium

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#79] opened 2021-05-10 19:42 UTC
Solving a "vacuum" equilibrium (J=0) is different from a "0-pressure" equilibrium (JxB=0).  The existing code only solves JxB=grad(p).  An objective function could be added that minimized the current (J^rho=J^theta=J^zeta=0) instead of minimizing the force balance (F_rho=F_beta=0).  
New input file options and internal logic would be required to determine which case to run.

**Comment by f0uriest** [comment] 2022-06-21 18:44
@ddudt is this resolved with the new ``CurrentDensity`` objective? Is there anything else we need to add from a UI standpoint?

**Comment by dpanici** [comment] 2022-06-25 00:27
On this topic, I get an error when trying to run this objective on master branch, unsure of the cause right now but we should add a test for this objective

```
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_755/3725171782.py in <module>
     46     objectives = (CurrentDensity()) # all equal weights but is that right?
     47     obj = ObjectiveFunction(objectives)
---> 48     eq.solve(verbose=3, ftol=1e-4,objective=obj,maxiter=100,xtol=1e-6,constraints=constraints);
     49 
     50 # do current density

~/DESC/desc/equilibrium.py in solve(self, objective, constraints, optimizer, ftol, xtol, gtol, maxiter, x_scale, options, verbose, copy)
    353             )
    354 
--> 355         result = optimizer.optimize(
    356             eq,
    357             objective,

~/DESC/desc/optimize/optimizer.py in optimize(self, eq, objective, constraints, ftol, xtol, gtol, x_scale, verbose, maxiter, options)
    280             timer.disp("linear constraint factorize")
    281 
--> 282         x0_reduced = project(objective.x(eq))
    283 
    284         if verbose > 0:

~/DESC/desc/objectives/utils.py in project(x)
    117     def project(x):
    118         """Project a full state vector into the reduced optimization vector."""
--> 119         x_reduced = jnp.dot(Z.T, (x - xp)[unfixed_idx])
    120         return jnp.atleast_1d(jnp.squeeze(x_reduced))
    121 

~/.local/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py in deferring_binary_op(self, other)
   6583     if not isinstance(other, _accepted_binop_types):
   6584       return NotImplemented
-> 6585     return binary_op(self, other)
   6586   return deferring_binary_op
   6587 

~/.local/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py in <lambda>(x, y)
   6587 
   6588 def _swap_args(f):
-> 6589   return lambda x, y: f(y, x)
   6590 
   6591 def _unimplemented_setitem(self, i, x):

    [... skipping hidden 13 frame]

~/.local/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py in <lambda>(x1, x2)
    677     fn = lambda x1, x2: lax_fn(*_promote_args_inexact(numpy_fn.__name__, x1, x2))
    678   else:
--> 679     fn = lambda x1, x2: lax_fn(*_promote_args(numpy_fn.__name__, x1, x2))
    680   fn = jit(fn, inline=True)
    681   if lax_doc:

    [... skipping hidden 4 frame]

~/.local/lib/python3.8/site-packages/jax/_src/lax/lax.py in _broadcasting_shape_rule(name, *avals)
   2370   if result_shape is None:
   2371     msg = '{} got incompatible shapes for broadcasting: {}.'
-> 2372     raise TypeError(msg.format(name, ', '.join(map(str, map(tuple, shapes)))))
   2373   return result_shape
   2374 

TypeError: sub got incompatible shapes for broadcasting: (91,), (104,).
```

**Comment by f0uriest** [comment] 2022-06-25 14:38
My hunch is its something to do with not constraining iota - the size difference of 13 is probably the unconstrained iota terms, so we're probably being inconsistent in how the constraints are built or something

**Comment by ddudt** [comment] 2022-06-25 19:41
Yeah the issue is with the constraints. I know how to implement it correctly in a script -- I'm working on a way to call the "vacuum" objective from an input file.

**Closed** 2022-06-28 18:12 UTC
Labels: Urgent, funtionality, theory, enhancement
