### ISSUE TITLE
Ability to change resolution of SplineProfiles

### ISSUE THREAD

**Issue by rahulgaur104** [PlasmaControl/DESC#851] opened 2024-02-02 17:59 UTC
For the PowerSeriesProfile class one can change the number of coefficients of the input profiles during optimization.
But this ability is not available for the SplineProfile class. 

I think it would be nice to have a spline with varying number of knots during an optmization so that the user can vary the knots and add more optimizable parameters (more freedom) to their optimization.

I'll try to add this feature.

**Comment by ddudt** [comment] 2024-02-02 19:29
Related to #849. I think it would be good to have a standalone util function, and then `SplineProfile.change_resolution` can call that under the hood.

**Comment by dpanici** [comment] 2024-08-20 19:09
as duplicate of #849

**Closed by dpanici** 2024-08-20 19:09 UTC
Labels: enhancement, EZ-fix, hackathon
