### ISSUE TITLE
Objective for coil/vessel distance

### ISSUE THREAD

**Issue by kianorr** [PlasmaControl/DESC#947] opened 2024-03-20 00:45 UTC
For CSX

**Comment by f0uriest** [comment] 2024-04-05 00:44
This might be a duplicate of #900. If we make the objective work for generic surfaces then it could work for coil/plasma or coil/vessel distance

**Comment by dpanici** [comment] 2024-05-15 20:08
Will be closed by #977

**Closed** 2024-06-26 00:57 UTC
Labels: duplicate, coil
